### ISSUE TITLE
Thanks for your work

### ISSUE THREAD

**Issue by mjio** [hiway/po#2]
Hi Harshad,

Thanks for creating this library and all the comments you made, I enjoyed reading through the config files. I'm using Vim together with a custom keyboard layout and found it helpful to start from scratch and to create my own config.

By the way, I'm also disabling the arrow keys on my keyboard. In case you want to include this to the `01_lockdown.vim` file.

```
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
```

**Comment by hiway** [comment]
@mjio woah! I missed seeing this earlier. Thank you! I'm glad it was useful to you, I'll add this as optional - however, since I want to make this friendly for new people, I wouldn't impose this restriction by default.
